var AdsProtocol ={
	"name": "ADS Protocol",
	"description": "This is used to specify the ADS protocol",
	"version": "0.0.1",
	"author" : "Cyril Praz",
	"types":{
		"BOOL"            : { "bytelength": 1,     "bufferType":"uint8"    },
		"BYTE"            : { "bytelength": 1,     "bufferType":"uint8"    },
		"USINT"           : { "bytelength": 1,     "bufferType":"uint8"    },
		"SINT"            : { "bytelength": 1,     "bufferType":"int8"     },
		"UINT"            : { "bytelength": 2,     "bufferType":"uint16LE" },
		"WORD"            : { "bytelength": 2,     "bufferType":"uint16LE" },
		"INT"             : { "bytelength": 2,     "bufferType":"int16LE"  },
		"DWORD"           : { "bytelength": 4,     "bufferType":"uint32LE" },
		"UDINT"           : { "bytelength": 4,     "bufferType":"uint32LE" },
		"DINT"            : { "bytelength": 4,     "bufferType":"int32LE"  },
		"LINT"            : { "bytelength": 8,     "bufferType":"uint8"    },
		"ULINT"           : { "bytelength": 8,     "bufferType":"uint8"    },
		"REAL"            : { "bytelength": 4,     "bufferType":"floatLE"  },
		"LREAL"           : { "bytelength": 8,     "bufferType":"doubleLE" },
		"TIME"            : { "bytelength": null,  "bufferType":"buffer"   },
		"TIME_OF_DAY"     : { "bytelength": null,  "bufferType":"buffer"   },
		"DATE"            : { "bytelength": null,  "bufferType":"buffer"   },
		"DATE_AND_TIME"   : { "bytelength": null,  "bufferType":"buffer"   },
		"INT16"           : { "bytelength": 2,     "bufferType":"int16LE"    },
		"BUFFER"            : { "bytelength": null,  "bufferType":"buffer"   },
		"STRING"          : { "bytelength": null,  "bufferType":"buffer"   }
	},
	"cmd_id":{
		"READ_DEVICE_INFO"  : 1,
		"READ"              : 2,
		"WRITE"             : 3,
		"READ_STATE"        : 4,
		"WRITE_CONTROL"     : 5,
		"ADD_NOTIFICATION"  : 6,
		"DEL_NOTIFICATION"  : 7,
		"NOTIFICATION"      : 8,
		"READ_WRITE"        : 9			
	},
	"states":[  
		{ "id": 0,    "name": "invalid"        },
		{ "id": 1,    "name": "idle"           },
		{ "id": 2,    "name": "reset"          },
		{ "id": 3,    "name": "initialisation" },
		{ "id": 4,    "name": "start"          },
		{ "id": 5,    "name": "run"            },
		{ "id": 6,    "name": "stop"           },
		{ "id": 7,    "name": "save config"    },
		{ "id": 8,    "name": "load config"    },
		{ "id": 9,    "name": "power failure"  },
		{ "id": 10,   "name": "power good"     },
		{ "id": 11,   "name": "error"          },
		{ "id": 12,   "name": "shutdown"       },
		{ "id": 13,   "name": "supend"         },
		{ "id": 14,   "name": "resume"         },
		{ "id": 15,   "name": "config"         },
		{ "id": 16,   "name": "reconfig"       }
	],
	"notify":{
		"CYCLIC"            : 3,
		"ONCHANGE"          : 4
	},
	"services":{
		"SYMTAB"			: 0xF000,
		"SYMNAME"			: 0xF001,
		"SYMVAL"			: 0xF002,
		"SYM_HNDBYNAME"		: 0xF003,
		"SYM_VALBYNAME"		: 0xF004,
		"SYM_VALBYHND"		: 0xF005,
		"SYM_RELEASEHND"	: 0xF006,
		"SYM_INFOBYNAME"	: 0xF007,
		"SYM_VERSION"		: 0xF008,
		"SYM_INFOBYNAMEEX"	: 0xF009,
		"SYM_DOWNLOAD"		: 0xF00A,
		"SYM_UPLOAD"		: 0xF00B,
		"SYM_UPLOADINFO"	: 0xF00C,
		"SYMNOTE"			: 0xF010,
		"IOIMAGE_RWIB"		: 0xF020,
		"IOIMAGE_RWIX"		: 0xF021,
		"IOIMAGE_RISIZE"	: 0xF025,
		"IOIMAGE_RWOB"		: 0xF030,
		"IOIMAGE_RWOX"		: 0xF031,
		"IOIMAGE_RWOSIZE"	: 0xF035,
		"IOIMAGE_CLEARI"	: 0xF040,
		"IOIMAGE_CLEARO"	: 0xF050,
		"IOIMAGE_RWIOB"		: 0xF060,
		"DEVICE_DATA"		: 0xF100,
		"DEVDATA_ADSSTATE"	: 0x0000,
		"DEVDATA_DEVSTATE"	: 0x0002
	},
	"errors":[
		{ "id": 1 , "msg": "Internal error"},
        { "id": 2 , "msg": "No Rtime"},
        { "id": 3 , "msg": "Allocation locked memory error"},
        { "id": 4 , "msg": "Insert mailbox error"},
        { "id": 5 , "msg": "Wrong receive HMSG"},
        { "id": 6 , "msg": "target port not found"},
        { "id": 7 , "msg": "target machine not found"},
        { "id": 8 , "msg": "Unknown command ID"},
        { "id": 9 , "msg": "Bad task ID"},
        { "id": 10, "msg": "No IO"},
        { "id": 11, "msg": "Unknown AMS command"},
        { "id": 12, "msg": "Win 32 error"},
        { "id": 13, "msg": "Port not connected"},
        { "id": 14, "msg": "Invalid AMS length"},
        { "id": 15, "msg": "Invalid AMS Net ID"},
        { "id": 16, "msg": "Low Installation level"},
        { "id": 17, "msg": "No debug available"},
        { "id": 18, "msg": "Port disabled"},
        { "id": 19, "msg": "Port already connected"},
        { "id": 20, "msg": "AMS Sync Win32 error"},
        { "id": 21, "msg": "AMS Sync Timeout"},
        { "id": 22, "msg": "AMS Sync AMS error"},
        { "id": 23, "msg": "AMS Sync no index map"},
        { "id": 24, "msg": "Invalid AMS port"},
        { "id": 25, "msg": "No memory"},
        { "id": 26, "msg": "TCP send error"},
        { "id": 27, "msg": "Host unreachable"},                 
        { "id": 1792, "msg":"error class <device error>"},
        { "id": 1793, "msg":"Service is not supported by server"},
        { "id": 1794, "msg":"invalid index group"},
        { "id": 1795, "msg":"invalid index offset"},
        { "id": 1796, "msg":"reading/writing not permitted"},
        { "id": 1797, "msg":"parameter size not correct"},
        { "id": 1798, "msg":"invalid parameter value(s)"},
        { "id": 1799, "msg":"device is not in a ready state"},
        { "id": 1800, "msg":"device is busy"},
        { "id": 1801, "msg":"invalid context (must be in Windows)"},
        { "id": 1802, "msg":"out of memory"},
        { "id": 1803, "msg":"invalid parameter value(s)"},
        { "id": 1804, "msg":"not found (files, ...)"},
        { "id": 1805, "msg":"syntax error in command or file"},
        { "id": 1806, "msg":"objects do not match"},
        { "id": 1807, "msg":"object already exists"},
        { "id": 1808, "msg":"symbol not found"},
        { "id": 1809, "msg":"symbol version invalid"},
        { "id": 1810, "msg":"server is in invalid state"},
        { "id": 1811, "msg":"AdsTransMode not supported"},
        { "id": 1812, "msg":"Notification handle is invalid"},
        { "id": 1813, "msg":"Notification client not registered"},
        { "id": 1814, "msg":"no more notification handles"},
        { "id": 1815, "msg":"size for watch too big"},
        { "id": 1816, "msg":"device not initialized"},
        { "id": 1817, "msg":"device has a timeout"},
        { "id": 1818, "msg":"query interface failed"},
        { "id": 1819, "msg":"wrong interface required"},
        { "id": 1820, "msg":"class ID is invalid"},
        { "id": 1821, "msg":"object ID is invalid"},
        { "id": 1822, "msg":"request is pending"},
        { "id": 1823, "msg":"request is aborted"},
        { "id": 1824, "msg":"signal warning"},
        { "id": 1825, "msg":"invalid array index"},
        { "id": 1826, "msg":"symbol not active -> release handle and try again"},
        { "id": 1827, "msg":"access denied"},
        { "id": 1856, "msg":"Error class <client error>"},
        { "id": 1857, "msg":"invalid parameter at service"},
        { "id": 1858, "msg":"polling list is empty"},
        { "id": 1859, "msg":"var connection already in use"},
        { "id": 1860, "msg":"invoke ID in use"},
        { "id": 1861, "msg":"timeout elapsed"},
        { "id": 1862, "msg":"error in win32 subsystem"},
        { "id": 1863, "msg":"Invalid client timeout value"},
        { "id": 1864, "msg":"ads-port not opened"},
        { "id": 1872, "msg":"internal error in ads sync"},
        { "id": 1873, "msg":"hash table overflow"},
        { "id": 1874, "msg":"key not found in hash"},
        { "id": 1875, "msg":"no more symbols in cache"},
        { "id": 1876, "msg":"invalid response received"},
        { "id": 1877, "msg":"sync port is locked"}
	],
	"frames":{
		"TCP_HEAD"      :{ "size": 6  },
		"AMS_HEAD"      :{ "size": 32 },
		"INDEX_GRP"     :{ "size": 4  },
		"INDEX_OFFSET"  :{ "size": 4  },
		"LENGTH"        :{ "size": 4  },
		"ADS_STATE"     :{ "size": 2  },
		"DEVICE_STATE"  :{ "size": 2  },
		"TRANSMOD"      :{ "size": 4  },
		"MAX_DELAY"     :{ "size": 4  },
		"CYCLE_TIME"    :{ "size": 4  },
		"NOTIF_RESERVED":{ "size": 16 },
		"NOTIF_HANDLE"  :{ "size": 4  }
	}



}
module.exports = exports = AdsProtocol;